.PHONY = all wii gc wii-clean gc-clean

default: wii

clean: wii-clean gc-clean

wii:
	$(MAKE) -f Makefile.Wii

wii-clean:
	$(MAKE) -f Makefile.Wii clean

gc:
	$(MAKE) -f Makefile.gc

gc-clean:
	$(MAKE) -f Makefile.gc clean
